#!usr/bin/python3

import urllib.request, json

#In order to make this to work, you need to get an Openweather map key AND your city name
city = "YOUR_CITY_NAME"
api_key = "YOUR_OPENWEATHERMAP_API_KEY" 

weather = eval(str(urllib.request.urlopen("http://api.openweathermap.org/data/2.5/weather?q={}&APPID={}".format(city, api_key)).read())[2:-1])

info = weather["weather"][0]["description"].capitalize()
temp = int(float(weather["main"]["temp"]) - 272.15)

print("%s, %i °C" % (info, temp))
